"""Added tokenization field

Revision ID: e95f9f59d096
Revises: 7bb137e7d999
Create Date: 2021-01-15 18:24:37.676869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95f9f59d096'
down_revision = '7bb137e7d999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('tokenization', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'tokenization')
    # ### end Alembic commands ###
